version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command:
      bash -c 'rm -f tmp/pids/*.pid && rails s -b 0.0.0.0'
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amarket_development
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
