default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: db

development:
  <<: *default
  database: amarket_development

test:
  <<: *default
  database: amarket_test

production:
  <<: *default
  database: amarket
